routes/web.php
<?php

use App\Mail\HasilSwab;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false]);
              Route::get('/', 'LandingController@landing')->name('landing');
Route::get('/getkota/{id}', 'LocationController@getkota')->name('getkota');
Route::get('/getkecamatan/{id}', 'LocationController@getkecamatan')->name('getkecamatan');

//Pendaftaran
Route::get('/pendaftaran/{id}','PendaftaranController@pendaftaran')->name('pendaftaran');
Route::get('/daftar/{code}','PendaftaranController@pendaftaranqrcode')->name('pendaftaranqrcode');
Route::post('/daftar','PendaftaranController@daftar')->name('daftar');
Route::get('/hasil/{code}','HasilController@hasilemail')->name('result');

Route::get('/contohpdf','HasilController@testpdf');





Route::prefix('dashboard')->group(function () {
    Route::get('/', 'HomeController@index')->name('home');

    Route::middleware(['auth', 'superadmin'])->group(function () {

        Route::resource('settings/user', 'UserController');
        Route::resource('settings/lab', 'LabController');
        Route::post('settings/user/changepassword/{id}','UserController@changepassword')->name('super.changepassword');
        Route::get('settings/lab/downloadqrcode/{no_lab}','LabController@downloadqrcode')->name('super.downloadqrcode');

        Route::get('settings/jenistest','PengaturanController@JenisTest')->name('jenistest');
        Route::get('settings/jenistest/create','PengaturanController@addviewJenisTest')->name('addviewjenistest');
        Route::post('settings/jenistest/add','PengaturanController@addJenisTest')->name('addjenistest');
        Route::get('settings/jenistest/edit/{id}','PengaturanController@editJenistest')->name('editjenistest');
        Route::post('settings/jenistest/update/{id}','PengaturanController@updateJenisTest')->name('updatejenistest');

        Route::get('settings/addon','PengaturanController@addon')->name('addon');
        Route::get('settings/createviewaddon','PengaturanController@createviewaddon')->name('createviewaddon');
        Route::post('settings/createaddon','PengaturanController@createaddon')->name('createaddon');
        Route::get('settings/addon/edit/{id}','PengaturanController@editaddon')->name('editaddon');
        Route::post('settings/addon/update/{id}','PengaturanController@updateaddon')->name('updateaddon');

        Route::get('report','ReportController@report')->name('report');
        Route::get('printout','ReportController@printout')->name('printout');
        Route::get('hasilreport/{id}','ReportController@hasilsatu')->name('hasilsatu');

        Route::get('/finance','ReportFinanceController@index')->name('finance');
        Route::get('/finance/filter','ReportFinanceController@filter')->name('financeFilter');
        Route::get('/finance/export','ReportFinanceController@export')->name('financeExport');

     });
     Route::middleware(['auth', 'admin'])->group(function () {

         Route::get('/transactions','TransactionController@transactions')->name('admin.transactions');
         Route::get('/transactions/{id}','TransactionController@transactionlab')->name('admin.transactionlab');
         Route::get('/transactions/reorder/{transaction_code}/{lab_id}','TransactionController@reorder')->name('admin.reorder');
         Route::post('/transactions/reordersubmit','TransactionController@reordersubmit')->name('admin.reordersubmit');
         Route::get('/transactions/detail/{code}','TransactionController@transactiondetail')->name('admin.transactiondetail');
         Route::get('/transactions/invoice/{code}','TransactionController@transactioninvoice')->name('admin.transactioninvoice');
         Route::get('/transactions/viewinvoice/{code}','TransactionController@transactionviewinvoice')->name('admin.transactionviewinvoice');
         Route::post('/transactions/pay','TransactionController@transactionpay')->name('admin.transactionpay');
         Route::post('/transactions/delete','TransactionController@transactiondelete')->name('admin.transactiondelete');

         Route::get('/hasilswab','HasilController@pilihlab')->name('hasil.pilihlab');
         Route::get('/hasilswab/{id}','HasilController@datapasien')->name('hasil.datapasien');
         Route::get('/hasilpdf/{id}/{no_lab}','HasilController@hasilpdf')->name('hasil.hasilpdf');

         Route::post('/pindahdata','HasilController@pindahlab')->name('hasil.pindah');
     });
     Route::middleware(['auth', 'dokter'])->group(function () {

         Route::get('/swab','SwabController@pilihlab')->name('dokter.pilihlab');
         Route::get('/swab/{id}','SwabController@datapasien')->name('dokter.datapasien');
         Route::get('/swab/input/{code}','SwabController@swabinput')->name('dokter.swabinput');
         Route::post('/swab/update','SwabController@swabupdate')->name('dokter.swabupdate');
         Route::get('/hasil','SwabController@hasiltest')->name('dokter.hasil');
     });
});

resources/views/includes/footer.blade.php
<!-- Footer -->
<div class="hk-footer-wrap container">
    <footer class="footer">
        <div class="row">
            <div class="col-md-6 col-sm-12">
                <p>Powered by<a href="#" class="text-dark" target="_blank">FastSwab</a> © 2021</p>
            </div>
        </div>
    </footer>
</div>
<!-- /Footer -->

resources/views/includes/scripts.blade.php
    <!-- jQuery -->
    <script src="{{asset('assets/vendors/jquery/dist/jquery.min.js')}}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{{asset('assets/vendors/popper.js/dist/umd/popper.min.js')}}"></script>
    <script src="{{asset('assets/vendors/bootstrap/dist/js/bootstrap.min.js')}}"></script>

    <!-- Slimscroll JavaScript -->
    <script src="{{asset('assets/dist/js/jquery.slimscroll.js')}}"></script>

    <!-- Fancy Dropdown JS -->
    <script src="{{asset('assets/dist/js/dropdown-bootstrap-extended.js')}}"></script>

    <!-- FeatherIcons JavaScript -->
    <script src="{{asset('assets/dist/js/feather.min.js')}}"></script>

    <!-- Toggles JavaScript -->
    <script src="{{asset('assets/vendors/jquery-toggles/toggles.min.js')}}"></script>
    <script src="{{asset('assets/dist/js/toggle-data.js')}}"></script>  

	<!-- Counter Animation JavaScript -->
	<script src="{{asset('assets/vendors/waypoints/lib/jquery.waypoints.min.js')}}"></script>
	<script src="{{asset('assets/vendors/jquery.counterup/jquery.counterup.min.js')}}"></script>

	<!-- EChartJS JavaScript -->
    <script src="{{asset('assets/vendors/echarts/dist/echarts-en.min.js')}}"></script>

	<!-- Sparkline JavaScript -->
    <script src="{{asset('assets/vendors/jquery.sparkline/dist/jquery.sparkline.min.js')}}"></script>

	<!-- Vector Maps JavaScript -->
    <script src="{{asset('assets/vendors/vectormap/jquery-jvectormap-2.0.3.min.js')}}"></script>
    <script src="{{asset('assets/vendors/vectormap/jquery-jvectormap-world-mill-en.js')}}"></script>
    <script src="{{asset('assets/dist/js/vectormap-data.js')}}"></script>

	<!-- Owl JavaScript -->
    <script src="{{asset('assets/vendors/owl.carousel/dist/owl.carousel.min.js')}}"></script>

	<!-- Toastr JS -->
    <script src="{{asset('assets/vendors/jquery-toast-plugin/dist/jquery.toast.min.js')}}"></script>

    <!-- Init JavaScript -->
    <script src="{{asset('assets/dist/js/init.js')}}"></script>
	<script src="{{asset('assets/dist/js/dashboard-data.js')}}"></script>

resources/views/includes/style.blade.php
<!-- Favicon -->
    <link rel="shortcut icon" href="{{asset('assets/images/fastswab.png')}}">
    <link rel="icon" href="{{asset('assets/images/fastswab.png')}}" type="image/x-icon">

	<!-- vector map CSS -->
    <link href="{{asset('assets/vendors/vectormap/jquery-jvectormap-2.0.3.css')}}" rel="stylesheet" type="text/css" />

    <!-- Toggles CSS -->
    <link href="{{asset('assets/vendors/jquery-toggles/css/toggles.css')}}" rel="stylesheet" type="text/css">
    <link href="{{asset('assets/vendors/jquery-toggles/css/themes/toggles-light.css')}}" rel="stylesheet" type="text/css">

	<!-- Toastr CSS -->
    <link href="{{asset('assets/vendors/jquery-toast-plugin/dist/jquery.toast.min.css')}}" rel="stylesheet" type="text/css">

    <!-- Custom CSS -->
    <link href="{{asset('assets/dist/css/style.css')}}" rel="stylesheet" type="text/css">

resources/views/includes/topnavbar.blade.php
<!-- Top Navbar -->
<nav class="navbar navbar-expand-xl navbar-light fixed-top hk-navbar">
    <a id="navbar_toggle_btn" class="navbar-toggle-btn nav-link-hover" href="javascript:void(0);"><span class="feather-icon"><i data-feather="menu"></i></span></a>
    <a class="navbar-brand" href="#">
        <img class="brand-img d-inline-block" src="{{asset('assets/images/fastswab.png')}}" alt="brand" width="60" />
    </a>
    <ul class="navbar-nav hk-navbar-content">
        {{-- <li class="nav-item dropdown dropdown-notifications">
            <a class="nav-link dropdown-toggle no-caret" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span class="feather-icon"><i data-feather="bell"></i></span><span class="badge-wrap"><span class="badge badge-primary badge-indicator badge-indicator-sm badge-pill pulse"></span></span></a>
            <div class="dropdown-menu dropdown-menu-right" data-dropdown-in="fadeIn" data-dropdown-out="fadeOut">
                <h6 class="dropdown-header">Notifications <a href="javascript:void(0);" class="">View all</a></h6>
                <div class="notifications-nicescroll-bar">
                    <a href="javascript:void(0);" class="dropdown-item">
                        <div class="media">
                            <div class="media-img-wrap">
                                <div class="avatar avatar-sm">
                                    <img src="{{asset('assets/dist/img/avatar1.jpg')}}" alt="user" class="avatar-img rounded-circle">
                                </div>
                            </div>
                            <div class="media-body">
                                <div>
                                    <div class="notifications-text"><span class="text-dark text-capitalize">Evie Ono</span> accepted your invitation to join the team</div>
                                    <div class="notifications-time">12m</div>
                                </div>
                            </div>
                        </div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="javascript:void(0);" class="dropdown-item">
                        <div class="media">
                            <div class="media-img-wrap">
                                <div class="avatar avatar-sm">
                                    <img src="{{asset('dist/img/avatar2.jpg')}}" alt="user" class="avatar-img rounded-circle">
                                </div>
                            </div>
                            <div class="media-body">
                                <div>
                                    <div class="notifications-text">New message received from <span class="text-dark text-capitalize">Misuko Heid</span></div>
                                    <div class="notifications-time">1h</div>
                                </div>
                            </div>
                        </div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="javascript:void(0);" class="dropdown-item">
                        <div class="media">
                            <div class="media-img-wrap">
                                <div class="avatar avatar-sm">
                                    <span class="avatar-text avatar-text-primary rounded-circle">
                                            <span class="initial-wrap"><span><i class="zmdi zmdi-account font-18"></i></span></span>
                                    </span>
                                </div>
                            </div>
                            <div class="media-body">
                                <div>
                                    <div class="notifications-text">You have a follow up with<span class="text-dark text-capitalize"> Pangong head</span> on <span class="text-dark text-capitalize">friday, dec 19</span> at <span class="text-dark">10.00 am</span></div>
                                    <div class="notifications-time">2d</div>
                                </div>
                            </div>
                        </div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="javascript:void(0);" class="dropdown-item">
                        <div class="media">
                            <div class="media-img-wrap">
                                <div class="avatar avatar-sm">
                                    <span class="avatar-text avatar-text-success rounded-circle">
                                            <span class="initial-wrap"><span>A</span></span>
                                    </span>
                                </div>
                            </div>
                            <div class="media-body">
                                <div>
                                    <div class="notifications-text">Application of <span class="text-dark text-capitalize">Sarah Williams</span> is waiting for your approval</div>
                                    <div class="notifications-time">1w</div>
                                </div>
                            </div>
                        </div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="javascript:void(0);" class="dropdown-item">
                        <div class="media">
                            <div class="media-img-wrap">
                                <div class="avatar avatar-sm">
                                    <span class="avatar-text avatar-text-warning rounded-circle">
                                            <span class="initial-wrap"><span><i class="zmdi zmdi-notifications font-18"></i></span></span>
                                    </span>
                                </div>
                            </div>
                            <div class="media-body">
                                <div>
                                    <div class="notifications-text">Last 2 days left for the project</div>
                                    <div class="notifications-time">15d</div>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </li> --}}
        <li class="nav-item dropdown dropdown-authentication">
            <a class="nav-link dropdown-toggle no-caret" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <div class="media">
                    <div class="media-body">
                        <span>{{Auth::user()->name}}<i class="zmdi zmdi-chevron-down"></i></span>
                    </div>
                </div>
            </a>
            <div class="dropdown-menu dropdown-menu-right" data-dropdown-in="flipInX" data-dropdown-out="flipOutX">
                <a class="dropdown-item" href="{{ route('logout') }}"
                onclick="event.preventDefault();
                              document.getElementById('logout-form').submit();">
                 <i class="dropdown-icon zmdi zmdi-power"></i><span>Log out</span></a>
            </div>
            <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                @csrf
            </form>
        </li>
    </ul>
</nav>
<!-- /Top Navbar -->

resources/views/includes/verticalnav.blade.php
<!-- Vertical Nav -->
<nav class="hk-nav hk-nav-dark">
    <a href="javascript:void(0);" id="hk_nav_close" class="hk-nav-close"><span class="feather-icon"><i data-feather="x"></i></span></a>
    <div class="nicescroll-bar">
        <div class="navbar-nav-wrap">
            <ul class="navbar-nav flex-column">
                <li class="nav-item {{ Request::is('/') ? 'active' : '' }}">
                    <a class="nav-link " href="{{route('home')}}">
                        <span class="feather-icon"><i data-feather="pie-chart"></i></span>
                        <span class="nav-link-text">Dashboard</span>
                    </a>
                </li>
                @if(Auth::user()->role==1 ||Auth::user()->role==4)
                <li class="nav-item {{ Request::is('dashboard/transactions*') ? 'active' : '' }}">
                    <a class="nav-link " href="{{route('admin.transactions')}}">
                        <span class="feather-icon"><i data-feather="dollar-sign"></i></span>
                        <span class="nav-link-text">Transaction</span>
                    </a>
                </li>
                <li class="nav-item {{ Request::is('dashboard/hasilswab*') ? 'active' : '' }}">
                    <a class="nav-link " href="{{route('hasil.pilihlab')}}">
                        <span class="feather-icon"><i data-feather="printer"></i></span>
                        <span class="nav-link-text">Hasil Swab</span>
                    </a>
                </li>
                <li class="nav-item {{ Request::is('dashboard/swab*') ? 'active' : '' }}">
                    <a class="nav-link " href="{{route('dokter.pilihlab')}}">
                        <span class="feather-icon"><i data-feather="edit-3"></i></span>
                        <span class="nav-link-text">SwabTest</span>
                    </a>
                </li>
                <li class="nav-item {{ Request::is('dashboard/report*') ? 'active' : '' }}">
                    <a class="nav-link " href="{{ route('report') }}">
                        <span class="feather-icon"><i data-feather="book"></i></span>
                        <span class="nav-link-text">Report</span>
                    </a>
                </li>
                <li class="nav-item {{ Request::is('dashboard/finance*') ? 'active' : '' }}">
                    <a class="nav-link " href="{{ route('finance') }}">
                        <span class="feather-icon"><i data-feather="book"></i></span>
                        <span class="nav-link-text">Report Finance</span>
                    </a>
                </li>
                <li class="nav-item {{ Request::is('dashboard/settings*') ? 'active' : '' }}">
                    <a class="nav-link" href="javascript:void(0);" data-toggle="collapse" data-target="#pengaturan">
                        <span class="feather-icon"><i data-feather="server"></i></span>
                        <span class="nav-link-text">Pengaturan</span>
                    </a>
                    <ul id="pengaturan" class="nav flex-column collapse collapse-level-1">
                        @if(Auth::user()->role==1)
                        <li class="nav-item {{ Request::is('dashboard/user*') ? 'active' : '' }}">
                            <ul class="nav flex-column">
                                <li class="nav-item">
                                    <a class="nav-link" href="{{route('user.index')}}">User</a>
                                </li>
                            </ul>
                        </li>
                        @endif
                        <li class="nav-item {{ Request::is('dashboard/lab*') ? 'active' : '' }}">
                            <ul class="nav flex-column">
                                <li class="nav-item">
                                    <a class="nav-link" href="{{route('lab.index')}}">Lab</a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item {{ Request::is('dashboard/settings/jenistest*') ? 'active' : '' }}">
                            <ul class="nav flex-column">
                                <li class="nav-item">
                                    <a class="nav-link" href="{{route('jenistest')}}">Jenis Test</a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item {{ Request::is('dashboard/settings/addon*') ? 'active' : '' }}">
                            <ul class="nav flex-column">
                                <li class="nav-item">
                                    <a class="nav-link" href="{{route('addon')}}">Addon</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </li>
                @endif
                @if(Auth::user()->role==2)
                <li class="nav-item {{ Request::is('dashboard/transactions*') ? 'active' : '' }}">
                    <a class="nav-link " href="{{route('admin.transactionlab',Auth::user()->lab)}}">
                        <span class="feather-icon"><i data-feather="dollar-sign"></i></span>
                        <span class="nav-link-text">Transaction</span>
                    </a>
                </li>
                <li class="nav-item {{ Request::is('dashboard/hasilswab*') ? 'active' : '' }}">
                    <a class="nav-link " href="{{route('hasil.datapasien',Auth::user()->lab)}}">
                        <span class="feather-icon"><i data-feather="printer"></i></span>
                        <span class="nav-link-text">Hasil Swab</span>
                    </a>
                </li>
                @endif
                @if(Auth::user()->role==3)
                <li class="nav-item {{ Request::is('dashboard/swab*') ? 'active' : '' }}">
                    <a class="nav-link " href="{{route('dokter.datapasien',Auth::user()->lab)}}">
                        <span class="feather-icon"><i data-feather="edit-3"></i></span>
                        <span class="nav-link-text">SwabTest</span>
                    </a>
                </li>
                @endif
            </ul>
        </div>
    </div>
</nav>
<div id="hk_nav_backdrop" class="hk-nav-backdrop"></div>
<!-- /Vertical Nav -->