routes/web.php
<?php

use App\Mail\HasilSwab;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false]);
              Route::get('/', 'LandingController@landing')->name('landing');
Route::get('/getkota/{id}', 'LocationController@getkota')->name('getkota');
Route::get('/getkecamatan/{id}', 'LocationController@getkecamatan')->name('getkecamatan');

//Pendaftaran
Route::get('/pendaftaran/{id}','PendaftaranController@pendaftaran')->name('pendaftaran');
Route::get('/daftar/{code}','PendaftaranController@pendaftaranqrcode')->name('pendaftaranqrcode');
Route::post('/daftar','PendaftaranController@daftar')->name('daftar');
Route::get('/hasil/{code}','HasilController@hasilemail')->name('result');

Route::get('/contohpdf','HasilController@testpdf');





Route::prefix('dashboard')->group(function () {
    Route::get('/', 'HomeController@index')->name('home');

    Route::middleware(['auth', 'superadmin'])->group(function () {

        Route::resource('settings/user', 'UserController');
        Route::resource('settings/lab', 'LabController');
        Route::post('settings/user/changepassword/{id}','UserController@changepassword')->name('super.changepassword');
        Route::get('settings/lab/downloadqrcode/{no_lab}','LabController@downloadqrcode')->name('super.downloadqrcode');

        Route::get('settings/jenistest','PengaturanController@JenisTest')->name('jenistest');
        Route::get('settings/jenistest/create','PengaturanController@addviewJenisTest')->name('addviewjenistest');
        Route::post('settings/jenistest/add','PengaturanController@addJenisTest')->name('addjenistest');
        Route::get('settings/jenistest/edit/{id}','PengaturanController@editJenistest')->name('editjenistest');
        Route::post('settings/jenistest/update/{id}','PengaturanController@updateJenisTest')->name('updatejenistest');

        Route::get('settings/addon','PengaturanController@addon')->name('addon');
        Route::get('settings/createviewaddon','PengaturanController@createviewaddon')->name('createviewaddon');
        Route::post('settings/createaddon','PengaturanController@createaddon')->name('createaddon');
        Route::get('settings/addon/edit/{id}','PengaturanController@editaddon')->name('editaddon');
        Route::post('settings/addon/update/{id}','PengaturanController@updateaddon')->name('updateaddon');

        Route::get('report','ReportController@report')->name('report');
        Route::get('printout','ReportController@printout')->name('printout');
        Route::get('hasilreport/{id}','ReportController@hasilsatu')->name('hasilsatu');

        Route::get('/finance','ReportFinanceController@index')->name('finance');
        Route::get('/finance/filter','ReportFinanceController@filter')->name('financeFilter');
        Route::get('/finance/export','ReportFinanceController@export')->name('financeExport');

     });
     Route::middleware(['auth', 'admin'])->group(function () {

         Route::get('/transactions','TransactionController@transactions')->name('admin.transactions');
         Route::get('/transactions/{id}','TransactionController@transactionlab')->name('admin.transactionlab');
         Route::get('/transactions/reorder/{transaction_code}/{lab_id}','TransactionController@reorder')->name('admin.reorder');
         Route::post('/transactions/reordersubmit','TransactionController@reordersubmit')->name('admin.reordersubmit');
         Route::get('/transactions/detail/{code}','TransactionController@transactiondetail')->name('admin.transactiondetail');
         Route::get('/transactions/invoice/{code}','TransactionController@transactioninvoice')->name('admin.transactioninvoice');
         Route::get('/transactions/viewinvoice/{code}','TransactionController@transactionviewinvoice')->name('admin.transactionviewinvoice');
         Route::post('/transactions/pay','TransactionController@transactionpay')->name('admin.transactionpay');
         Route::post('/transactions/delete','TransactionController@transactiondelete')->name('admin.transactiondelete');

         Route::get('/hasilswab','HasilController@pilihlab')->name('hasil.pilihlab');
         Route::get('/hasilswab/{id}','HasilController@datapasien')->name('hasil.datapasien');
         Route::get('/hasilpdf/{id}/{no_lab}','HasilController@hasilpdf')->name('hasil.hasilpdf');

         Route::post('/pindahdata','HasilController@pindahlab')->name('hasil.pindah');
     });
     Route::middleware(['auth', 'dokter'])->group(function () {

         Route::get('/swab','SwabController@pilihlab')->name('dokter.pilihlab');
         Route::get('/swab/{id}','SwabController@datapasien')->name('dokter.datapasien');
         Route::get('/swab/input/{code}','SwabController@swabinput')->name('dokter.swabinput');
         Route::post('/swab/update','SwabController@swabupdate')->name('dokter.swabupdate');
         Route::get('/hasil','SwabController@hasiltest')->name('dokter.hasil');
     });
});

resources/views/pages/hasilswab.blade.php
@extends('layouts.index')
@section('title','Hasil Swab - Daftar Pasien')
@section('content')

@push('after-style')
<!-- Data Table CSS -->
<link href="{{asset('assets/vendors/datatables.net-dt/css/jquery.dataTables.min.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('assets/vendors/datatables.net-responsive-dt/css/responsive.dataTables.min.css')}}" rel="stylesheet" type="text/css" />

@endpush
<!-- Container -->
<div class="container-fluid mt-4">
	<!-- Title -->
	<div class="hk-pg-header align-items-top">
		<div class="px-50 py-19">
            <h2 class="hk-pg-title font-weight-600 mb-10">Hasil Swab - Daftar Pasien {{$lab->nama_lab}}</h2>
            <small>{{$lab->no_lab}}</small>
            <small>Jika berwarna merah berarti positif atau reaktif</small>
		</div>
	</div>
	<!-- /Title -->

	<!-- Row -->
	<div class="row">
		<div class="col-xl-12">
			<div class="card">
                <div class="card-body">
                    {{-- <a href="{{route('lab.create')}}" class="btn btn-primary mb-2">Create Lab</a> --}}
                    <div class="table-responsive">
                        <table class="table table-bordered" id="datable_1">
                            <thead>
                                <tr>
                                    <th>Code</th>
                                    <th>Nama</th>
                                    <th>Email</th>
                                    <th>Phone</th>
                                    <th>Pasien</th>
                                    <th>Tanggal Daftar</th>
                                    <th>#</th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
		</div>
	</div>
	<!-- /Row -->
</div>

<div class="modal fade" id="bayar" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Bayar</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form action="{{route('admin.transactionpay')}}" method="POST">
            @csrf
            <div class="modal-body">
                <p class="text-center">Tandai sudah bayar dan buat invoice?</p>
                <input type="hidden" id="idtrans" name="idtrans">
            </div>
            <div class="modal-footer justify-content-between">
                <button type="submit" class="btn btn-success">Yes</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </form>
      </div>
    </div>
  </div>

  <div class="modal fade" id="pindah" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form action="{{route('hasil.pindah')}}" method="POST">
            @csrf
            <div class="modal-body">
                <p class="text-center">Pindah Data Ke Lab?</p>
                <input type="hidden" id="idtrans" name="idtrans">
                <select name="lab" id="" class="form-control">
                    @foreach ($daftarlab as $item)
                    <option value="{{$item->id}}">{{$item->nama_lab}}</option>

                    @endforeach
                </select>
            </div>
            <div class="modal-footer justify-content-between">
                <button type="submit" class="btn btn-danger">Yes</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </form>
      </div>
    </div>
  </div>

@push('after-scripts')
    <!-- Data Table JavaScript -->
    <script src="{{asset('assets/vendors/datatables.net/js/jquery.dataTables.min.js')}}"></script>
    <script src="{{asset('assets/vendors/datatables.net-bs4/js/dataTables.bootstrap4.min.js')}}"></script>
    <script src="{{asset('assets/vendors/datatables.net-dt/js/dataTables.dataTables.min.js')}}"></script>
    <script src="{{asset('assets/vendors/datatables.net-buttons/js/dataTables.buttons.min.js')}}"></script>
    <script src="{{asset('assets/vendors/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js')}}"></script>
    <script src="{{asset('assets/vendors/datatables.net-buttons/js/buttons.flash.min.js')}}"></script>
    <script src="{{asset('assets/vendors/jszip/dist/jszip.min.js')}}"></script>
    <script src="{{asset('assets/vendors/pdfmake/build/pdfmake.min.js')}}"></script>
    <script src="{{asset('assets/vendors/pdfmake/build/vfs_fonts.js')}}"></script>
    <script src="{{asset('assets/vendors/datatables.net-buttons/js/buttons.html5.min.js')}}"></script>
    <script src="{{asset('assets/vendors/datatables.net-buttons/js/buttons.print.min.js')}}"></script>
    <script src="{{asset('assets/vendors/datatables.net-responsive/js/dataTables.responsive.min.js')}}"></script>

    <script>
        $(document).ready(function() {
            $('#datable_1').DataTable({
                responsive: false,
                autoWidth: false,
                language: { search: "",
                searchPlaceholder: "Search",
                sLengthMenu: "_MENU_items"

                },
                processing:true,
                serverSide:true,
                ordering:true,
                ajax:{
                    url:'{!! url()->current() !!}',
                },
                columns:[
                    { data:'code',name:'code'},
                    { data:'nama',name:'nama'},
                    { data:'email',name:'email'},
                    { data:'phone',name:'phone'},
                    {
                        data:'pasien',
                        name:'pasien',
                        orderable:'false',
                        searchable: 'false',
                    },
                    {
                        data:'tanggal',
                        name:'tanggal',
                        orderable:'false',
                        searchable: 'false',
                    },
                    {
                        data:'action',
                        name:'action',
                        orderable:'false',
                        searchable: 'false',
                    },

                ]
            });
    });
    </script>
    <script>
        $('#bayar').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget) // Button that triggered the modal
            var idtrans = button.data('id')
            var modal = $(this)
            modal.find('.modal-body #idtrans').val(idtrans);
        })
        $('#pindah').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget) // Button that triggered the modal
            var idtrans = button.data('id')
            var modal = $(this)
            modal.find('.modal-body #idtrans').val(idtrans);
        })
    </script>

@if ($message = Session::get('success'))
    <script>
         $(document).ready(function() {
        $.toast({
		heading: 'Well done!',
		text: '<p>{{$message}}</p>',
		position: 'top-right',
		loaderBg:'#00acf0',
		class: 'jq-toast-primary',
		hideAfter: 3500,
		stack: 6,
		showHideTransition: 'fade'
    });
});
    </script>


@endif
@if ($message = Session::get('error'))
    <script>
         $(document).ready(function() {
        $.toast({
		heading: 'Well done!',
		text: '<p>{{$message}}</p>',
		position: 'top-right',
		loaderBg:'#00acf0',
		class: 'jq-toast-danger',
		hideAfter: 3500,
		stack: 6,
		showHideTransition: 'fade'
    });
});
    </script>


@endif
@endpush
<!-- /Container -->
@endsection

resources/views/pages/labedit.blade.php
@extends('layouts.index')
@section('title','Edit - Lab')
@section('content')

@push('after-style')

<link rel="stylesheet" href="{{asset('dropify/css/dropify.css')}}">


@endpush
<!-- Container -->
<div class="container mt-xl-50 mt-sm-30 mt-15">
	<!-- Title -->
	<div class="hk-pg-header align-items-top">
		<div>
			<h2 class="hk-pg-title font-weight-600 mb-10">Edit Lab</h2>
		</div>
	</div>
	<!-- /Title -->

	<!-- Row -->
	<div class="row">
		<div class="col-xl-12">
            <div class="card">
                <div class="card-body">
                    <form action="{{route('lab.update',$lab->id)}}" method="post" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                          <label for="no_lab">No Lab</label>
                          <input type="text" class="form-control @error('no_lab') is-invalid @enderror" id="no_lab" placeholder="Masukan No Lab" name="no_lab" value="{{$lab->no_lab}}">
                          @error('no_lab')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                          @enderror
                        </div>
                        <div class="form-group">
                          <label for="nama_lab">Nama Lab</label>
                          <input type="text" class="form-control @error('nama_lab') is-invalid @enderror" id="nama_lab" placeholder="Masukan Nama Lab" name="nama_lab" value="{{$lab->nama_lab}}">
                          @error('nama_lab')
                          <span class="invalid-feedback" role="alert">
                              <strong>{{ $message }}</strong>
                          </span>
                         @enderror
                        </div>
                        <div class="form-group">
                          <label for="provinsi">Provinsi</label>
                            <select name="provinsi" id="provinsi" class="form-control @error('provinsi') is-invalid @enderror">
                                <option value="">-Pilih Provinsi-</option>
                                @foreach ($provinsi as $prov)
                                    <option value="{{$prov->nama}}" idprov="{{$prov->id}}" @if($lab->provinsi == $prov->nama) selected @endif>{{$prov->nama}}</option>
                                @endforeach
                            </select>
                        @error('provinsi')
                          <span class="invalid-feedback" role="alert">
                              <strong>{{ $message }}</strong>
                          </span>
                         @enderror
                        </div>
                        <div class="form-group">
                          <label for="kota">Kota/Kabupaten</label>
                            <select name="kota" id="kota" class="form-control @error('kota') is-invalid @enderror">
                                <option value="">-Pilih Kota-</option>
                                @if($lab->kota)
                                <option value="{{$lab->kota}}" selected>{{$lab->kota}}</option>
                                @endif
                            </select>
                        @error('kota')
                          <span class="invalid-feedback" role="alert">
                              <strong>{{ $message }}</strong>
                          </span>
                         @enderror
                        </div>
                        <div class="form-group">
                          <label for="kota">Kecamatan</label>
                            <select name="kecamatan" id="kecamatan" class="form-control @error('kecamatan') is-invalid @enderror">
                                <option value="">-Pilih Kecamatan-</option>
                                @if($lab->kecamatan)
                                <option value="{{$lab->kecamatan}}" selected>{{$lab->kecamatan}}</option>
                                @endif
                            </select>
                        @error('kecamatan')
                          <span class="invalid-feedback" role="alert">
                              <strong>{{ $message }}</strong>
                          </span>
                         @enderror
                        </div>
                        <div class="form-group">
                            <label for="alamat">Alamat</label>
                            <textarea name="alamat" id="alamat" cols="30" rows="5" class="form-control @error('alamat') is-invalid @enderror" >{{$lab->alamat}}</textarea>
                            @error('alamat')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="pengawas">Pengawas</label>
                            <input type="text" class="form-control @error('pengawas') is-invalid @enderror" id="pengawas" placeholder="Masukan Nama Pengawas Lab" name="pengawas" value="{{$lab->pengawas}}">
                            @error('pengawas')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                           @enderror
                        </div>
                        <div class="form-group">
                            <label for="tanda_tangan">Tanda Tangan (untuk menampilkan di hasil swab)</label>
                            <div style="width: 50%">
                                <input type="file" class="dropify" name="tanda_tangan" accept="image/*" data-allowed-file-extensions="jpg jpeg png" data-default-file="{{asset($lab->tanda_tangan)}}">
                            </div>
                            @error('tanda_tangan')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                           @enderror
                        </div>
                        <div class="form-group">
                            <label for="tanda_tangan">Alamat Header (menampilkan di atas output)</label>
                            <div style="width: 100%">
                                <input type="file" class="dropify" name="header_template" accept="image/*" data-allowed-file-extensions="jpg jpeg png" data-default-file="{{asset($lab->header_template)}}" >
                            </div>
                            @error('header_template')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                           @enderror
                        </div>
                        <label for="type">Type</label>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="type" id="exampleRadios1" value="1" @if ($lab->type == 1)
                                checked
                            @endif>
                            <label class="form-check-label" for="exampleRadios1">
                             DriveThru
                            </label>
                          </div>
                          <div class="form-check mb-2">
                            <input class="form-check-input" type="radio" name="type" id="exampleRadios2" value="2" @if ($lab->type == 2)
                            checked
                        @endif>
                            <label class="form-check-label" for="exampleRadios2">
                              Home Service
                            </label>
                          </div>
                        <button type="submit" class="btn btn-primary">Update</button>
                    </form>
                </div>
            </div>
		</div>
	</div>
	<!-- /Row -->
</div>

@push('after-scripts')
<script type="text/javascript">
    $(document).ready(function() {
    $('select[name="provinsi"]').on('change', function(){
        var provinsiID = $("option:selected", this).attr("idprov");
        if(provinsiID) {
            $.ajax({
                url: "/getkota/"+provinsiID,
                type:"GET",
                dataType:"json",
                success:function(result) {
                    console.log(result);
                    $('select[name="kota"]').empty();
                    $('select[name="kota"]').append('<option value="" idkota="">-Pilih Kota-</option>');
                    $.each(result.kota_kabupaten, function(id,nama){
                        $('select[name="kota"]').append('<option value="'+ nama.nama +'" idkota="'+ nama.id +'">' + nama.nama + '</option>');
                    });
                },
            });
        } else {
            $('select[name="kota"]').empty();
            $('select[name="kota"]').append('<option value="">-Pilih Kota-</option>');

        }
    });
    $('select[name="kota"]').on('change', function(){
        var kotaID = $("option:selected", this).attr("idkota");
        if(kotaID) {
            $.ajax({
                url: "/getkecamatan/"+kotaID,
                type:"GET",
                dataType:"json",
                success:function(result) {
                    $('select[name="kecamatan"]').empty();
                    $('select[name="kecamatan"]').append('<option value="">-Pilih Kecamatan-</option>');
                    $.each(result.kecamatan, function(key, value){
                        $('select[name="kecamatan"]').append('<option value="'+ value.nama +'">' + value.nama + '</option>');
                    });
                },
            });
        } else {
            $('select[name="kecamatan"]').empty();
            $('select[name="kecamatan"]').append('<option value="">-Pilih Kecamatan-</option>');
        }
    });
});
</script>
<script>
    // Add the following code if you want the name of the file appear on select
    $(".custom-file-input").on("change", function() {
      var fileName = $(this).val().split("\\").pop();
      $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
    });
    </script>
    <script src="{{asset('dropify/js/dropify.js')}}"></script>
    <script>
        $(document).ready(function(){
            // Basic
            $('.dropify').dropify();
        });
    </script>
@endpush
<!-- /Container -->
@endsection

resources/views/pages/user.blade.php
@extends('layouts.index')
@section('title','Data - User')
@section('content')

@push('after-style')
<!-- Data Table CSS -->
<link href="{{asset('assets/vendors/datatables.net-dt/css/jquery.dataTables.min.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('assets/vendors/datatables.net-responsive-dt/css/responsive.dataTables.min.css')}}" rel="stylesheet" type="text/css" />

@endpush
<!-- Container -->
<div class="container mt-xl-50 mt-sm-30 mt-15">
	<!-- Title -->
	<div class="hk-pg-header align-items-top">
		<div>
			<h2 class="hk-pg-title font-weight-600 mb-10">User</h2>
		</div>
	</div>
	<!-- /Title -->

	<!-- Row -->
	<div class="row">
		<div class="col-xl-12">
			<div class="card">
                <div class="card-body">
                    <a href="{{route('user.create')}}" class="btn btn-primary mb-2">Create User</a>
                    <div class="table-responsive">
                        <table class="table table-bordered" id="datable_1">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Nama</th>
                                    <th>Username</th>
                                    <th>Role</th>
                                    <th>Aksi</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($users as $user)
                                <tr>
                                    <td>{{$loop->iteration}}</td>
                                    <td>{{$user->name}}</td>
                                    <td>{{$user->username}}</td>
                                    @if ($user->role ==2)
                                    <td>Admin</td>
                                    @else
                                    <td>Dokter</td>
                                    @endif
                                        <td>
                                            <a href="{{route('user.edit',$user->id)}}" class="btn btn-warning px-2"><i class="fa fa-edit"></i>Edit</a>
                                            <button type="button" class="btn btn-danger px-2" data-id="{{$user->id}}" data-toggle="modal" data-target="#deleteuser"><i class="fa fa-trash"></i>Hapus</button>
                                        </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
		</div>
	</div>
	<!-- /Row -->
</div>

<div class="modal fade" id="deleteuser" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Delete User</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form action="{{route('user.destroy','deleteuser')}}" method="POST">
            @csrf
            @method('delete')
            <div class="modal-body">

                <p class="text-center">Delete User ini?</p>
                <input type="hidden" id="iduser" name="iduser">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-danger">Delete</button>
            </div>
        </form>
      </div>
    </div>
  </div>

@push('after-scripts')
    <!-- Data Table JavaScript -->
    <script src="{{asset('assets/vendors/datatables.net/js/jquery.dataTables.min.js')}}"></script>
    <script src="{{asset('assets/vendors/datatables.net-bs4/js/dataTables.bootstrap4.min.js')}}"></script>
    <script src="{{asset('assets/vendors/datatables.net-dt/js/dataTables.dataTables.min.js')}}"></script>
    <script src="{{asset('assets/vendors/datatables.net-buttons/js/dataTables.buttons.min.js')}}"></script>
    <script src="{{asset('assets/vendors/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js')}}"></script>
    <script src="{{asset('assets/vendors/datatables.net-buttons/js/buttons.flash.min.js')}}"></script>
    <script src="{{asset('assets/vendors/jszip/dist/jszip.min.js')}}"></script>
    <script src="{{asset('assets/vendors/pdfmake/build/pdfmake.min.js')}}"></script>
    <script src="{{asset('assets/vendors/pdfmake/build/vfs_fonts.js')}}"></script>
    <script src="{{asset('assets/vendors/datatables.net-buttons/js/buttons.html5.min.js')}}"></script>
    <script src="{{asset('assets/vendors/datatables.net-buttons/js/buttons.print.min.js')}}"></script>
    <script src="{{asset('assets/vendors/datatables.net-responsive/js/dataTables.responsive.min.js')}}"></script>

    <script>
        $(document).ready(function() {
            $('#datable_1').DataTable({
                responsive: true,
                autoWidth: false,
                language: { search: "",
                searchPlaceholder: "Search",
                sLengthMenu: "_MENU_items"

                }
            });
    });
    </script>
    <script>
        $('#deleteuser').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget) // Button that triggered the modal
            var iduser = button.data('id')
            var modal = $(this)
            modal.find('.modal-body #iduser').val(iduser);
        })
    </script>

@if ($message = Session::get('success'))
    <script>
         $(document).ready(function() {
        $.toast({
		heading: 'Well done!',
		text: '<p>{{$message}}</p>',
		position: 'top-right',
		loaderBg:'#00acf0',
		class: 'jq-toast-primary',
		hideAfter: 3500,
		stack: 6,
		showHideTransition: 'fade'
    });
});
    </script>


@endif
@if ($message = Session::get('error'))
    <script>
         $(document).ready(function() {
        $.toast({
		heading: 'Well done!',
		text: '<p>{{$message}}</p>',
		position: 'top-right',
		loaderBg:'#00acf0',
		class: 'jq-toast-danger',
		hideAfter: 3500,
		stack: 6,
		showHideTransition: 'fade'
    });
});
    </script>


@endif
@endpush
<!-- /Container -->
@endsection